const flightDetails = [
  {
    id: 1,
    pid: 1,
    planesList: [
      {
        id: 1,
        from: "Chennai",
        to: "Colombo",
        depart: "10:00",
        arrive: "11:25",
        airline: "JetBlue Airways",
        totalHrs: "1h 25m",
        price: "14,369",
      },
      {
        id: 2,
        from: "Mumbai",
        to: "Colombo",
        depart: "20:40",
        arrive: "23:05",
        airline: "JetBlue Airways",
        totalHrs: "2h 25m",
        price: "20,103",
      },
      {
        id: 3,
        from: "Delhi",
        to: "Colombo",
        depart: "22:15",
        arrive: "01:50",
        airline: "JetBlue Airways",
        totalHrs: "3h 35m",
        price: "27,653",
      },
      {
        id: 4,
        from: "Chennai",
        to: "Colombo",
        depart: "01:00",
        arrive: "02:30",
        airline: "IndiGo",
        totalHrs: "1h 30m",
        price: "14,737",
      },
      {
        id: 5,
        from: "Mumbai",
        to: "Colombo",
        depart: "02:05",
        arrive: "04:30",
        airline: "IndiGo",
        totalHrs: "2h 35m",
        price: "19,650",
      },
      {
        id: 6,
        from: "Delhi",
        to: "Colombo",
        depart: "10:00",
        arrive: "01:35",
        airline: "IndiGo",
        totalHrs: "3h 35m",
        price: "24,859",
      },
      {
        id: 7,
        from: "Chennai",
        to: "Colombo",
        depart: "03:10",
        arrive: "04:35",
        airline: "Delta Air Lines",
        totalHrs: "1h 20m",
        price: "14,558",
      },
      {
        id: 8,
        from: "Mumbai",
        to: "Colombo",
        depart: "09:30",
        arrive: "12:00",
        airline: "Delta Air Lines",
        totalHrs: "2h 30m",
        price: "20,250",
      },
      {
        id: 9,
        from: "Delhi",
        to: "Colombo",
        depart: "20:30",
        arrive: "23:05",
        airline: "Delta Air Lines",
        totalHrs: "3h 35m",
        price: "27,235",
      },
    ],
  },
  {
    id: 2,
    pid: 2,
    planesList: [
      {
        id: 1,
        from: "Kolkata",
        to: "Thailand",
        depart: "00:30",
        arrive: "04:30",
        airline: "JetBlue Airways",
        totalHrs: "2h 30m",
        price: "12,424",
      },
      {
        id: 2,
        from: "Mumbai",
        to: "Thailand",
        depart: "23:35",
        arrive: "05:35",
        airline: "JetBlue Airways",
        totalHrs: "4h 30m",
        price: "19,505",
      },
      {
        id: 3,
        from: "Banglore",
        to: "Thailand",
        depart: "00:30",
        arrive: "05:55",
        airline: "JetBlue Airways",
        totalHrs: "3h 55m",
        price: "17,090",
      },
      {
        id: 4,
        from: "Kolkata",
        to: "Thailand",
        depart: "03:10",
        arrive: "04:35",
        airline: "IndiGo",
        totalHrs: "2h 30m",
        price: "13,037",
      },
      {
        id: 5,
        from: "Mumbai",
        to: "Thailand",
        depart: "02:35",
        arrive: "8:35",
        airline: "IndiGo",
        totalHrs: "4h 30m",
        price: "17,390",
      },
      {
        id: 6,
        from: "Banglore",
        to: "Thailand",
        depart: "05:45",
        arrive: "11:20",
        airline: "IndiGo",
        totalHrs: "4h 05m",
        price: "16,020",
      },
      {
        id: 7,
        from: "Kolkata",
        to: "Thailand",
        depart: "01:00",
        arrive: "02:30",
        airline: "Delta Air Lines",
        totalHrs: "2h 30m",
        price: "12,520",
      },
      {
        id: 8,
        from: "Mumbai",
        to: "Thailand",
        depart: "07:45",
        arrive: "13:25",
        airline: "Delta Air Lines",
        totalHrs: "4h 10m",
        price: "18,010",
      },
      {
        id: 9,
        from: "Banglore",
        to: "Thailand",
        depart: "07:45",
        arrive: "01:20",
        airline: "Delta Air Lines",
        totalHrs: "4h 05m",
        price: "16,545",
      },
    ],
  },
  {
    id: 3,
    pid: 3,
    planesList: [
      {
        id: 1,
        from: "Delhi",
        to: "Kathmandu",
        depart: "11:10",
        arrive: "13:05",
        airline: "JetBlue Airways",
        totalHrs: "1h 40m",
        price: "11,193",
      },
      {
        id: 2,
        from: "Mumbai",
        to: "Kathmandu",
        depart: "11:25",
        arrive: "14:20",
        airline: "JetBlue Airways",
        totalHrs: "2h 40m",
        price: "15,551",
      },
      {
        id: 3,
        from: "Ahmedabad",
        to: "Kathmandu",
        depart: "14:55",
        arrive: "19:35",
        airline: "JetBlue Airways",
        totalHrs: "4h 25m",
        price: "18,734",
      },
      {
        id: 4,
        from: "Delhi",
        to: "Kathmandu",
        depart: "07:00",
        arrive: "09:05",
        airline: "IndiGo",
        totalHrs: "1h 50m",
        price: "11,372",
      },
      {
        id: 5,
        from: "Mumbai",
        to: "Kathmandu",
        depart: "15:20",
        arrive: "17:40",
        airline: "IndiGo",
        totalHrs: "2h 35m",
        price: "14,210",
      },
      {
        id: 6,
        from: "Ahmedabad",
        to: "Kathmandu",
        depart: "05:55",
        arrive: "12:00",
        airline: "IndiGo",
        totalHrs: "4h 20m",
        price: "17,090",
      },
      {
        id: 7,
        from: "Delhi",
        to: "Kathmandu",
        depart: "12:55",
        arrive: "14:45",
        airline: "Delta Air Lines",
        totalHrs: "1h 45m",
        price: "11,747",
      },
      {
        id: 8,
        from: "Mumbai",
        to: "Kathmandu",
        depart: "11:05",
        arrive: "14:40",
        airline: "Delta Air Lines",
        totalHrs: "2h 40m",
        price: "14,950",
      },
      {
        id: 9,
        from: "Ahmedabad",
        to: "Kathmandu",
        depart: "07:50",
        arrive: "14:00",
        airline: "Delta Air Lines",
        totalHrs: "4h 15m",
        price: "16,800",
      },
    ],
  },
  {
    id: 4,
    pid: 4,
    planesList: [
      {
        id: 1,
        from: "Kolkata",
        to: "Bangladesh",
        depart: "11:30",
        arrive: "13:00",
        airline: "JetBlue Airways",
        totalHrs: "1h 00m",
        price: "10,011",
      },
      {
        id: 2,
        from: "Mumbai",
        to: "Bangladesh",
        depart: "09:40",
        arrive: "13:10",
        airline: "JetBlue Airways",
        totalHrs: "3h 00m",
        price: "13,110",
      },
      {
        id: 3,
        from: "Chennai",
        to: "Bangladesh",
        depart: "13:55",
        arrive: "17:05",
        airline: "JetBlue Airways",
        totalHrs: "2h 40m",
        price: "12,800",
      },
      {
        id: 4,
        from: "Kolkata",
        to: "Bangladesh",
        depart: "14:05",
        arrive: "15:35",
        airline: "IndiGo",
        totalHrs: "1h 00m",
        price: "11,309",
      },
      {
        id: 5,
        from: "Mumbai",
        to: "Bangladesh",
        depart: "07:25",
        arrive: "10:45",
        airline: "IndiGo",
        totalHrs: "2h 50m",
        price: "13,600",
      },
      {
        id: 6,
        from: "Chennai",
        to: "Bangladesh",
        depart: "14:05",
        arrive: "17:15",
        airline: "IndiGo",
        totalHrs: "2h 45m",
        price: "12,250",
      },
      {
        id: 7,
        from: "Kolkata",
        to: "Bangladesh",
        depart: "08:45",
        arrive: "10:10",
        airline: "Delta Air Lines",
        totalHrs: "0h 55m",
        price: "10,544",
      },
      {
        id: 8,
        from: "Mumbai",
        to: "Bangladesh",
        depart: "14:10",
        arrive: "16:30",
        airline: "Delta Air Lines",
        totalHrs: "2h 50m",
        price: "14,150",
      },
      {
        id: 9,
        from: "Chennai",
        to: "Bangladesh",
        depart: "10:45",
        arrive: "12:55",
        airline: "Delta Air Lines",
        totalHrs: "2h 40m",
        price: "12,660",
      },
    ],
  },
  {
    id: 5,
    pid: 5,
    planesList: [
      {
        id: 1,
        from: "Mumbai",
        to: "Maldives",
        depart: "09:30",
        arrive: "11:45",
        airline: "JetBlue Airways",
        totalHrs: "2h 45m",
        price: "18,366",
      },
      {
        id: 2,
        from: "Kochi",
        to: "Maldives",
        depart: "10:10",
        arrive: "11:30",
        airline: "JetBlue Airways",
        totalHrs: "1h 20m",
        price: "15,300",
      },
      {
        id: 3,
        from: "Banglore",
        to: "Maldives",
        depart: "13:05",
        arrive: "15:00",
        airline: "JetBlue Airways",
        totalHrs: "2h 05m",
        price: "22,560",
      },
      {
        id: 4,
        from: "Mumbai",
        to: "Maldives",
        depart: "10:40",
        arrive: "13:00",
        airline: "IndiGo",
        totalHrs: "2h 50m",
        price: "16,879",
      },
      {
        id: 5,
        from: "Kochi",
        to: "Maldives",
        depart: "12:15",
        arrive: "01:20",
        airline: "IndiGo",
        totalHrs: "1h 10m",
        price: "14,995",
      },
      {
        id: 6,
        from: "Banglore",
        to: "Maldives",
        depart: "03:00",
        arrive: "05:10",
        airline: "IndiGo",
        totalHrs: "2h 10m",
        price: "22,900",
      },
      {
        id: 7,
        from: "Mumbai",
        to: "Maldives",
        depart: "01:30",
        arrive: "03:45",
        airline: "Delta Air Lines",
        totalHrs: "2h 45m",
        price: "12,520",
      },
      {
        id: 8,
        from: "Kochi",
        to: "Maldives",
        depart: "02:15",
        arrive: "04:30",
        airline: "Delta Air Lines",
        totalHrs: "1h 20m",
        price: "15,050",
      },
      {
        id: 9,
        from: "Banglore",
        to: "Maldives",
        depart: "21:15",
        arrive: "23:25",
        airline: "Delta Air Lines",
        totalHrs: "2h 10m",
        price: "23,060",
      },
    ],
  },
  {
    id: 6,
    pid: 6,
    planesList: [
      {
        id: 1,
        from: "Thiruvananthapuram",
        to: "Singapore",
        depart: "23:25",
        arrive: "06:40",
        airline: "JetBlue Airways",
        totalHrs: "4h 45m",
        price: "13,828",
      },
      {
        id: 2,
        from: "Mumbai",
        to: "Singapore",
        depart: "23:35",
        arrive: "7:50",
        airline: "JetBlue Airways",
        totalHrs: "5h 45m",
        price: "18,369",
      },
      {
        id: 3,
        from: "Hyderabad",
        to: "Singapore",
        depart: "01:35",
        arrive: "08:55",
        airline: "JetBlue Airways",
        totalHrs: "4h 50",
        price: "25,359",
      },
      {
        id: 4,
        from: "Thiruvananthapuram",
        to: "Singapore",
        depart: "22:25",
        arrive: "05:40",
        airline: "IndiGo",
        totalHrs: "2h 30m",
        price: "13,037",
      },
      {
        id: 5,
        from: "Mumbai",
        to: "Singapore",
        depart: "12:00",
        arrive: "20:15",
        airline: "IndiGo",
        totalHrs: "5h 45m",
        price: "18,099",
      },
      {
        id: 6,
        from: "Hyderabad",
        to: "Singapore",
        depart: "23:00",
        arrive: "6:20",
        airline: "IndiGo",
        totalHrs: "4h 50m",
        price: "24,199",
      },
      {
        id: 7,
        from: "Thiruvananthapuram",
        to: "Singapore",
        depart: "21:25",
        arrive: "04:40",
        airline: "Delta Air Lines",
        totalHrs: "2h 30m",
        price: "13,520",
      },
      {
        id: 8,
        from: "Mumbai",
        to: "Singapore",
        depart: "01:10",
        arrive: "21:25",
        airline: "Delta Air Lines",
        totalHrs: "5h 55m",
        price: "17,999",
      },
      {
        id: 9,
        from: "Hyderabad",
        to: "Singapore",
        depart: "05:35",
        arrive: "12:10",
        airline: "Delta Air Lines",
        totalHrs: "4h 45m",
        price: "24,810",
      },
    ],
  },
];

export default flightDetails;
